spring.application.name=HandZ6Api
# Conexión MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/handz6?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=bufon317
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor (opcional, por defecto 8080)
server.port=8080
# Carpeta donde se guardan los logos
app.upload.dir=uploads/logos
# URL base para acceder a las imágenes
app.base.url=http://localhost:8080